### ISSUE TITLE
I can not right click in androidstudio when launch MacGusture

### ISSUE THREAD

**Issue by lipangit** [MacGesture/MacGesture#20] opened 2015-10-26 02:30 UTC
Same as title

**Comment by CodeFalling** [comment] 2015-10-26 02:42
oh really?I had this problem before at #9.I thought it was caused by java.But everything works well in appcode,so I close the issue.

Now it seems caused by Android Studio itself,**I don't know how to fix it in fact.But you can just pick Android Studio into block filter in preference for now.**

**Comment by jiegec** [comment] 2016-03-04 12:48
It works now.

**Comment by jiegec** [comment] 2016-03-04 13:08
Wait, but in other java apps, it failed again. The bundle identifier of this app is empty.

**Comment by jiegec** [comment] 2016-03-04 13:15
@CodeFalling We are relying bundle identifier to filter the apps. But some java apps are not opened from .app.

**Comment by CodeFalling** [comment] 2016-03-04 13:19
@jiegec A design mistake. Process name would be better.But it will be a break change. Maybe we should fix this at something like `3.0.x` or `2.1.x`?

**Comment by jiegec** [comment] 2016-03-04 13:22
Yes. Put it off.

**Comment by jiegec** [comment] 2016-03-04 13:24
Now temporarily fixed in #26

**Comment by jiegec** [comment] 2017-10-24 08:11
Fixed in 2.2.3.

**Closed by jiegec** 2017-10-24 08:11 UTC
Labels: enhancement, help wanted
